AllCops:
  Exclude:
    - 'app/protobuf/**/*.rb'
    - 'bin/*'
    - 'db/schema.rb'
  SuggestExtensions: false

Layout/LineLength:
  Max: 140
  AllowedPatterns:
    - !ruby/regexp /\A *# /

inherit_from: .rubocop_todo.yml
