# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb75b482fba1a8d47b609b87fc1690c67620dbf935d0904c5808e55510621c4d4400e6fceaad1af040c4667f5edb0af5f4cef2d2bc641c69deff060643faf1fa

test:
  secret_key_base: 02556d779641bf197d2425e135391c8fdd437bce822d6c7c943e323e73ffa3a146bd3e23a4d8b588523e5897d0e8b32b466301f62d890ee9236ab0d1650f1822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
